export const quotes = [
  'Chanting brings peace to the restless mind.',
  'Consistency in japam leads to inner transformation.',
  'Every mantra repetition purifies the soul.',
  'Focus on the sound, not the count.',
  'Silence grows with every japam.',
  'Devotion is more important than perfection.',
  'One mala a day keeps negativity away.',
  'Your breath and mantra should become one.',
  'Japam is the bridge between mind and divine.',
  'Repeat with faith, not force.',
  'Steady practice turns effort into grace.',
  'Let the mantra polish the mirror of the mind.',
  'Where attention goes, devotion grows.',
  'Count with beads, connect with the heart.',
  'Even one sincere round changes the day.',
  'Soft mind, steady breath, sacred name.',
  'Japam is not speed; it is sincerity.',
  'The name you repeat becomes your shelter.',
  'Small daily practice creates deep inner strength.',
  'A quiet tongue can awaken a loud heart.',
  'Offer each mantra as a flower of gratitude.',
  'Patience in chanting becomes clarity in living.',
  'Do not chase experience; stay with remembrance.',
  'Discipline today becomes devotion tomorrow.',
  'Return to the mantra whenever the mind wanders.',
  'The holy name is heard best in humility.',
  'When the mind is scattered, chant slower.',
  'Regular japam is spiritual compounding.',
  'Let your mornings begin with sacred sound.',
  'In still repetition, worry slowly dissolves.',
  'Act without attachment to results. — Bhagavad Gita 2.47',
  'The self is not slain when the body is slain. — Bhagavad Gita 2.20',
  'A disciplined mind is the best friend of the self. — Bhagavad Gita 6.6',
  'From whatever one remembers at death, that one attains. — Bhagavad Gita 8.6',
  'Whatever you do, offer it to Me. — Bhagavad Gita 9.27',
  'Fix your mind on Me and you shall live in Me. — Bhagavad Gita 12.8',
  'The wise see with equal vision. — Bhagavad Gita 5.18',
  'Peace comes to the one free from craving and possessiveness. — Bhagavad Gita 2.71',
  'Yoga is skill in action. — Bhagavad Gita 2.50',
  'One who is steady in yoga remains balanced in success and failure. — Bhagavad Gita 2.48',
  'Raise yourself by yourself; do not degrade yourself. — Bhagavad Gita 6.5',
  'The mind is restless, but it is trained by practice and detachment. — Bhagavad Gita 6.35',
  'Among sacrifices, I am the sacrifice of japa. — Bhagavad Gita 10.25',
  'Faith shapes the person; as one’s faith, so one becomes. — Bhagavad Gita 17.3',
  'Abandon fear and take refuge in the Divine. — Bhagavad Gita 18.66',
  'Perform your duty with a calm heart.',
  'Chant first, complain later.',
  'When in doubt, do one more mala.',
  'A gentle pace with full attention is powerful.',
  'Silence after japam is part of japam.',
  'A focused minute is better than a distracted hour.',
  'Japam trains the mind to return home.',
  'Protect your practice like a sacred appointment.',
  'Deep devotion begins with simple repetition.',
  'Repeat the name until the name repeats itself.',
  'Inward calm is the true fruit of counting.',
  'The more you remember, the less you fear.',
  'Choose remembrance over restlessness.',
  'One bead at a time, one breath at a time.',
];

export const getRandomQuote = () => {
  const index = Math.floor(Math.random() * quotes.length);
  return quotes[index];
};